sql = """CREATE PROCEDURE sp_convert_json_to_table(
    in json_string NVARCHAR(10000)
)
BEGIN
DROP TABLE IF EXISTS tmp_matrix;
DROP TABLE IF EXISTS tmp_numbers;

CREATE TEMPORARY TABLE tmp_numbers (
  n INT PRIMARY KEY
);

INSERT INTO tmp_numbers (n)
SELECT a.n + b.n * 10 + c.n * 100
FROM
 (SELECT 0 n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
  UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) a
CROSS JOIN
 (SELECT 0 n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
  UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) b
CROSS JOIN
 (SELECT 0 n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
  UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) c;

CREATE TEMPORARY TABLE tmp_matrix (
  row_idx INT,
  col_idx INT,
  value   INT
);

INSERT INTO tmp_matrix (row_idx, col_idx, value)
SELECT
  r.n + 1 AS row_idx,
  c.n + 1 AS col_idx,
  JSON_VALUE(json_string, CONCAT('$[', r.n, '][', c.n, ']')) AS value
FROM tmp_numbers r
JOIN tmp_numbers c
WHERE
  r.n < JSON_LENGTH(json_string)
  AND c.n < JSON_LENGTH(JSON_EXTRACT(json_string, CONCAT('$[', r.n, ']')));

SELECT * FROM tmp_matrix
ORDER BY row_idx, col_idx;
END"""